# Generated by Django 4.1 on 2022-09-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='is_paid',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='is_shipped',
            new_name='shipped',
        ),
    ]
