# Generated by Django 4.1 on 2023-01-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_chinese_menuitem_chinese'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='Category',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='Chinese',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='Category', to='customer.category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='chinese',
            field=models.ManyToManyField(related_name='Chinese', to='customer.chinese'),
        ),
    ]
