# Generated by Django 4.1 on 2023-01-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_ordermodel_category_ordermodel_chinese_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=300)),
                ('phno', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='chinese',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='Chinese',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='item', to='customer.category'),
        ),
        migrations.DeleteModel(
            name='Chinese',
        ),
    ]
